language: python

python:
 - "3.8"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pandas

script: pytest

deploy:
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
